### ISSUE TITLE
Option to change to the default message responses

### ISSUE THREAD

**Issue by FocusZTV** [jagrosh/JDA-Utilities#111]
Could the option to be able to change the default message responses for things like the user not having permission, the command being on cooldown etc be added?

It would be nice to be able to change the formatting of it to make it match my bots more.

**Comment by zThana** [comment]
You're better off making your own class which takes care of that. Once you implement any other features into your bot that will be used often, you'll be creating a class for that anyways.

**Comment by jagrosh** [comment]
This will be possible once translation support is added, as you could simply override the default (english) messages.

**Comment by jagrosh** [comment]
#54
