### ISSUE TITLE
Cannot get all members of the guild

### ISSUE THREAD

**Issue by ghost** [jagrosh/JDA-Utilities#116]
Can you check this code?
This was working before.
Essentially it does not get all the members, only me and my bot... and I am always the lucky one.

I am on utilities version 3.0.4 and JDA version 4.2.0_198

`
class RandomMember : Command() {
init {
name = "random"
help = "I will print a random member of the sever, excluding the bots."
cooldown = 1
}

override fun execute(event:CommandEvent) {
    handleChannelException(event) {
        event.reply(
            "And the lucky one is... ${event.guild.members.filterNot {
                it.user.isBot
            }.random().effectiveName
            }"
        )
        event.message.addReaction("✅").queue()
    }
}
}
`

**Comment by Fabricio20** [comment]
This is not a JDA-Utilities issue. To be able to get all members of a guild, you need to enable the GUILD_MEMBERS _PRIVILEGED_ Gateway Intent as well as enable chunking in JDA. Intents are required for any bot after the 7th of this month, and privileged intents **require** verification for bots over 100 guilds.

You can read more about this here: [Gateway Intents and Member Cache Policy](https://github.com/DV8FromTheWorld/JDA/wiki/Gateway-Intents-and-Member-Cache-Policy)

**Comment by ghost** [comment]
Thanks, with your suggestion it indeed worked but I needed to enable presence too, and even change the cache policy to ONLINE.
Didn't have to enable chunking for some reason.
