### ISSUE TITLE
Doesn't work at all.

### ISSUE THREAD

**Issue by vadympop** [jagrosh/JDA-Utilities#119]
I create a base bot, it doesn't work at all

My main class:
```java
package jtools;

import com.jagrosh.jdautilities.command.CommandClient;
import com.jagrosh.jdautilities.command.CommandClientBuilder;
import com.jagrosh.jdautilities.commons.waiter.EventWaiter;
import net.dv8tion.jda.api.JDABuilder;
import net.dv8tion.jda.api.AccountType;
import net.dv8tion.jda.api.OnlineStatus;
import net.dv8tion.jda.api.entities.Activity;
import jtools.different.PingCommand;

public class BaseBot {

    public static void main(String[] args) throws Exception {
        EventWaiter waiter = new EventWaiter();
        CommandClientBuilder builder = new CommandClientBuilder();
        builder.setPrefix("j!")
                .setOwnerId("660110922865704980")
                .setHelpWord("help")
                .addCommand(new PingCommand());

        CommandClient client = builder.build();

        new JDABuilder(AccountType.BOT)
                .setToken("")
                .setActivity(Activity.playing("j!help"))
                .setStatus(OnlineStatus.IDLE)
                .addEventListeners(waiter, client)
                .build();
    }
}
```

PingCommand class:
``` java
package jtools.different;

import com.jagrosh.jdautilities.command.Command;
import com.jagrosh.jdautilities.command.CommandEvent;

public class PingCommand extends Command {
    public PingCommand(){
        this.name = "ping";
    }

    @Override
    protected void execute(CommandEvent commandEvent) {
        commandEvent.reply("Hello, my ping is " + commandEvent.getJDA().getGatewayPing());
    }
}
```

Please help me

**Comment by topi314** [comment]
update jda

**Comment by vadympop** [comment]
Latest version

**Comment by Horstexplorer** [comment]
You either are not on the latest version or are ignoring the big deprecated message. In either case update to the latest JDA with it's new factory methods.

**Comment by vadympop** [comment]
No, I have a latest version of JDA, but I have this
![Screenshot_62](https://user-images.githubusercontent.com/67959852/98977163-f97f9000-2520-11eb-8522-b6aa75d8d96b.png)

**Comment by RedDaedalus** [comment]
That's not an error, it's just a warning telling you to configure your logger.

**Comment by sebm253** [comment]
> 
> 
> That's not an error, it's just a warning telling you to configure your logger.

.. about which you can read more [here](https://github.com/DV8FromTheWorld/JDA/wiki/10\)-FAQ#why-is-there-a-warning-from-slf4j-when-starting-up)

**Comment by vadympop** [comment]
Ok. But why doesn't my code work at all?

**Comment by Horstexplorer** [comment]
> You either are not on the latest version or are ignoring the big deprecated message. In either case update to the latest JDA with it's new factory methods.

It doesnt work like this anymore. Have a look at the readme as it literally shows what to use instead.

**Comment by DManstrator** [comment]
Check the JDA [ReadMe](https://github.com/DV8FromTheWorld/JDA) and [Wiki](https://github.com/DV8FromTheWorld/JDA/wiki/19%29-Troubleshooting#my-event-listener-code-is-not-executed) since this is a general JDA issue, not a JDA-Utils issue. And please follow issue templates when seeing them.

**Comment by jagrosh** [comment]
Without more information it's impossible to help you debug. If you haven't already, I would recommend joining the [JDA server](https://discord.gg/8yCK9pA) and providing more info in the #jda-utilities channel.
