### ISSUE TITLE
Unicode emotji doesn't work with JDA 3.0.0_191

### ISSUE THREAD

**Issue by gt22** [jagrosh/JDA-Utilities#13]
If unicode emoji passed in `CommandClientBuilder#setEmojis` it will cause `NumberFormatException`, becouse when reacting `CommandEvent` tries to use `JDA#getEmoteById`, which throw `NFE` when givem string can't be parsed. Check in `CommandEvent` is for `null` return, and `try/catch` only for `PermissionException` so `NFE` catched in JDA only.

**Comment by Shengaero** [comment]
There is a fix coming for this soon.

**Comment by jagrosh** [comment]
This is already fixed, and a NumberFormatException cannot be thrown:
https://github.com/JDA-Applications/JDA-Utilities/blob/master/src/main/java/com/jagrosh/jdautilities/commandclient/CommandEvent.java#L311-L319
Make sure you're on the latest version.

**Comment by gt22** [comment]
I actually can't get `1.1` version, gradle can't find it.
build.gradle:
```groovy
apply plugin: 'java'

repositories {
    jcenter()
    mavenCentral()
}

dependencies {
    compile 'com.jagrosh:JDA-Utilities:1.1'
    compile 'net.dv8tion:JDA:3.0.0_191'
    compile 'com.google.code.gson:gson:2.8.0'
    compile 'org.jooq:jool:0.9.12'
}
```
(1.0 version with `me.jagrosh...` works fine)

**Comment by Shengaero** [comment]
```java
repositories {
    jcenter()
    maven { url 'https://dl.bintray.com/jagrosh/maven/' }
}

dependencies {
    compile 'net.dv8tion:JDA:3.0.0_191'
    compile 'com.jagrosh:JDA-Utilities:1.1'
}
```
Try this @gt22.

**Comment by gt22** [comment]
@TheMonitorLizard, thanks. I think this repo should be included in readme?

**Comment by Shengaero** [comment]
Yes, I'll make sure to include it in my PR once version 1.2 comes out 😄
