### ISSUE TITLE
Move to Maven Central

### ISSUE THREAD

**Issue by david-jng** [jagrosh/JDA-Utilities#133]
Got some issues during todays builds and found out, that Gradle won't support JCenter in future (https://blog.gradle.org/jcenter-shutdown).

My error log was: 
`The fail message is: Could not determine artifacts for com.jagrosh:jda-utilities:3.0.1`
During gradle build.

Therefore please move to MavenCentral (https://repo.maven.apache.org/maven2/)

**Comment by freya022** [comment]
You can always use jitpack if you're really interested.

Or use a [fork](https://github.com/Chew/JDA-Chewtils)

**Comment by david-jng** [comment]
> You can always use jitpack if you're really interested.
> 
> Or use a [fork](https://github.com/Chew/JDA-Chewtils)

Yep, but I miss some features for example MarkdownUtil

**Comment by freya022** [comment]
> > You can always use jitpack if you're really interested.
> > Or use a [fork](https://github.com/Chew/JDA-Chewtils)
> 
> Yep, but I miss some features for example MarkdownUtil

This is JDA class in no way related to JDA-Utilities, you can find the class [here](https://github.com/DV8FromTheWorld/JDA/blob/development/src/main/java/net/dv8tion/jda/api/utils/MarkdownUtil.java)

**Comment by david-jng** [comment]
> > > You can always use jitpack if you're really interested.
> > > Or use a [fork](https://github.com/Chew/JDA-Chewtils)
> > 
> > 
> > Yep, but I miss some features for example MarkdownUtil
> 
> This is JDA class in no way related to JDA-Utilities, you can find the class [here](https://github.com/DV8FromTheWorld/JDA/blob/development/src/main/java/net/dv8tion/jda/api/utils/MarkdownUtil.java)

Ok you're right, just found it. Thanks!

**Comment by jagrosh** [comment]
This is being moved to dv8's maven repository (the same one JDA is on), which will happen basically whenever someone who knows how to use gradle PRs an update to do that
