### ISSUE TITLE
[Proposal] new featrue

### ISSUE THREAD

**Issue by wackiest** [jagrosh/JDA-Utilities#135]
be able to make the bot deafen on vc join rather than have it deafened per server.

**Comment by Mr-LegitHD** [comment]
No

~ Gino Cicci

**Comment by Xeravax** [comment]
> be able to make the bot deafen on vc join rather than have it deafened per server.

Just deafen the bot though the [Guild#deafen](https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/entities/Guild.html#deafen(net.dv8tion.jda.api.entities.Member,boolean)) method.

JDA-Utils is dead at this moment, a replacement for JDA-U would be [ChewUtils](https://github.com/Chew/JDA-Chewtils) though!

**Comment by jagrosh** [comment]
This would be something you do via JDA, not JDA-Utils.
