### ISSUE TITLE
[Suggesstion] Mention as default prefix

### ISSUE THREAD

**Issue by Artuto** [jagrosh/JDA-Utilities#30]
Could be possible having 2 prefixes? Mentioning the bot (@Bot) or using its prefix (/, >>, !) so if the help command isnt on the bot's game you could simply mention it.

**Comment by Shengaero** [comment]
As for the request itself, this would be a fine feature, and you are free to fork, commit, and PR changes to make if you wish to do it yourself, or wait until 1.7 when we commit most of the changes.

In any case, I'll put this on `enhancement`.

I would advise renaming this Suggestion* and rewording the request as it's hard to understand and took me at least 3 reads to confirm exactly what you were suggesting. 😅

**Comment by jagrosh** [comment]
You can set a prefix and an altprefix; you could use the default prefix for the main and the real prefix as the alt

**Comment by Shengaero** [comment]
Implemented in b8d50ec for 1.7
