### ISSUE TITLE
[Sugestion] Translation

### ISSUE THREAD

**Issue by suchorski** [jagrosh/JDA-Utilities#33]
There is some files to change the translation?
Something like !help command: "For additional help, contact Zap#2504"

**Comment by Shengaero** [comment]
Do you mean like a language translation?

**Comment by suchorski** [comment]
yes... some properties files to translate without changing the code

**Comment by Shengaero** [comment]
This is already planned for next release, me and @jagrosh have been talking about it for the last two weeks.
It will not be a done through a file, but the implementation will have the same effect.
