### ISSUE TITLE
Suggestion: Use pagination on ordered menu

### ISSUE THREAD

**Issue by RuinTD** [jagrosh/JDA-Utilities#36]
Ordered menus, instead of being limited to 10 choices, should use pagination for more than ten items.

**Comment by Shengaero** [comment]
There is no plans to redirect function of different menus for overflow of options.
This is not even without consideration that the functions of both the OrderedMenu and Paginator are *completely* different.
If you wish to have a function like this, you are more than happy to implement your own `Menu` and `MenuBuilder`.

**Comment by jagrosh** [comment]
You can also consider modifying the Paginator or looking into the SelectionDialog if you need more options; the OrderedMenu is primarily for quick selection between just a few options (since it also supports typing the number/letter)
