### ISSUE TITLE
[Suggestion] being able to remove credits in the help menu.

### ISSUE THREAD

**Issue by imim332** [jagrosh/JDA-Utilities#40]
Hi,

Like the title says, in the help menu (AboutCommand) it would be better if we can manage some, like the credits for JDAUtils, not like we don't want to credit you guys but some of us just want to change that.

**Comment by jagrosh** [comment]
The AboutCommand (like its packaging suggests: jdautilities.commandclient.**examples**) is just an example command; you can write your own command, and even base it off the example as long as you follow the license.

**Comment by Shengaero** [comment]
I'm closing this as it is and always was irrelevant to the functionality of the library.

As stated by @jagrosh, you can create your own custom implementation of `AboutCommand.java`, or possibly copy it and make one or two tweaks (so long as you adhere to the rules of the [license](https://github.com/JDA-Applications/JDA-Utilities/blob/master/LICENSE.md)).
