### ISSUE TITLE
Something to send message without any event ? 

### ISSUE THREAD

**Issue by Jerem584** [jagrosh/JDA-Utilities#45]
Hey!

How can i send message Without any event, just with guild id

Thanks;

**Comment by MinnDevelopment** [comment]
You need at least a JDA instance and a channel id in order to send a message.
```java
JDA api = getJDA(); // getJDA() must be where you get your JDA instance from, a channel or field
String id = getChannelId(); // getChannelId() must return a text channel id to send the message to
api.getTextChannelById(id).sendMessage(getMessage()).queue();
```
It doesn't really matter where you get the ID and JDA instance, only matters that you get them.

**Comment by Shengaero** [comment]
This is more a question regarding the [JDA Library](https://GitHub.com/Dv8FromTheWorld/JDA) than this library.
