### ISSUE TITLE
Default Game Always Used

### ISSUE THREAD

**Issue by averen** [jagrosh/JDA-Utilities#63]
Regardless of using CommandClientBuilder#useDefaultGame, the default is always used. To mitigate this, the default value for Game on line 38 of CommandClientBuilder should be `null` since null is already checked for in CommandClientImpl#onReady.

**Comment by Shengaero** [comment]
Unfortunately this is *intended* behavior.
We have discussed this in the past, and ultimately we decided that simple and out-of-the-box support for things like the default game is a key feature we want to provide.

To disable the default game you simply need to provide `null` to `CommandClientBuilder#setGame`
```java
CommandClientBuilder builder = /* ... */;
builder.setGame(null);
```
Additionally, I don't think changing a legacy default for the sake of people who don't want to use the default game saving the cost of a single method call is not worth it at this point.
