### ISSUE TITLE
Bot doesn't react to clicks on reactions

### ISSUE THREAD

**Issue by Andre601** [jagrosh/JDA-Utilities#64]
I currently use the Slideshow and Slideshow builder for my bot.
When I run a command, does the bot generate the slideshow and add reactions.
But the bot doesn't notice the adding of reactions.

Some info:
I've set the EventWaiter in the [Main.java](https://github.com/Andre601/NekoBot/blob/master/src/main/java/net/andre601/core/Main.java#L45) as a new EventWaiter and get it later in the [CmdNeko.java](https://github.com/Andre601/NekoBot/blob/master/src/main/java/net/andre601/commands/fun/CmdNeko.java#L19-L20)
I then load 30 images through a function in the [HttpUtil.java](https://github.com/Andre601/NekoBot/blob/master/src/main/java/net/andre601/util/HttpUtil.java#L37-L46).
Then finally creating the slideshow in the [CmdNeko.java](https://github.com/Andre601/NekoBot/blob/master/src/main/java/net/andre601/commands/fun/CmdNeko.java#L57-L88).

Like mentioned before does the bot create the embed and adds the images (Shows the text "Image 1/30") but it just doesn't react, when you click on the reactions.
The bot has permission to manage messages and adding embeds and it also disables the slideshow after the timeout (changes the image).

Another Issue I also had was, that adding jda-utilities to the pom.xml as artifactId causes errors (bintray doesn't have this artifactId), while adding the different libraries (jda-utilities-menu and jda-utilities-common) works completely fine.

It would be so happy, if someone could help me with that issue.

**Comment by Sanduhr32** [comment]
You forgot to add the event waiter in the JDABuilders listeners...
How should it get the events without JDA providing them? 
This is no JDA nor Utilities issue. Join the JDA Guild for getting further support.
Githubs issue tracker is for bug reports and feature requests.

**Comment by Andre601** [comment]
So it would be `builder.addEventListener(waiter);` in the Main.java?

**Comment by Sanduhr32** [comment]
Yes ofc. But let's move to the official JDA guild if you need more support ;)
I am sure someone will be there for helping you.

**Comment by Andre601** [comment]
I'm not in that guild for different reasons.
Anyway, thank you for the quick help.

**Comment by Andre601** [comment]
Oh. before I forget: What about the other issue?
That one with the pom.xml

**Comment by Sanduhr32** [comment]
Sorry i use Gradle. But I really can advise you to get your support there when the shitposters (including me) are either offline or in mood for helping.

**Comment by Shengaero** [comment]
@Andre601 Your pom must be invalid in some way.
@jagrosh uses JDA-Utilities in many of his projects, including the [music bot](https://github.com/jagrosh/MusicBot) and [Vortex](https://github.com/jagrosh/Vortex). I'd suggest looking at their `pom.xml` files.
