### ISSUE TITLE
[Feature] .removeMessages(int count)

### ISSUE THREAD

**Issue by ABravePanda** [jagrosh/JDA-Utilities#65]
So, i'm not exactly sure if this is possible, I haven't found a way to do it. If it is possible.. im sorry im a noob... but anyways,

basically on any "TextChannel" object, theres a void method called **_.removeMessages(int count)_** that gets the amount of messages specified in the channel, and deletes them. This would be good for something like a purge command. If this already exists, this could be a way to make it easier..

Anyways, just a suggestion.
Thanks for reading!

**Comment by Shengaero** [comment]
The issue tracker is reserved for issues relating to JDA-Utilities, not JDA.

**Comment by ABravePanda** [comment]
Oh wow.. im.. just... wow kill me..

**Comment by jagrosh** [comment]
Also, this probably wouldn't be added because deleting the last X messages will always require at least 2 API calls and several permissions

**Comment by Shengaero** [comment]
@ABravePanda Please keep your responses appropriate, this is not a typical discord channel, I like to keep this issue tracker clean and professional.

If you have any responses that are not appropriate but would still like to say them for whatever reason, join the [JDA Discord](https://discord.gg/0hMr4ce0tIl3SLv5).

**Comment by ABravePanda** [comment]
I'm sorry? What did I say?
