### ISSUE TITLE
Error with AboutCommand

### ISSUE THREAD

**Issue by lyssieth** [jagrosh/JDA-Utilities#9]
Whenever I use `::about`, I get the following error, in Pastebin form. http://pastebin.com/H6SMmHGU

`new AboutCommand(Color.green.brighter(),
				                    "a (currently) small utility bot that is actively being developed. [GitHub](https://github.com/raxixor/EDI)",
				                    new String[] {"Easy to modify", "Requires knowledge of java to host yourself", "Actively developed"}),`

**Comment by Shengaero** [comment]
1) You forgot to add the "Permission..." Parameter, if you don't want to have an invite on your about just set it null, but you need to set it.
2) Check to make sure you're JDA is up to date.

**Comment by lyssieth** [comment]
I made my own version of the command, which works properly and in the exact way I want it to work.
But yes, 1. would've fixed it, if I hadn't.
