### ISSUE TITLE
EventWaiter doesn't handle consistently GuildMemberJoinEvent

### ISSUE THREAD

**Issue by ghost** [jagrosh/JDA-Utilities#97]
[download]: https://bintray.com/jagrosh/maven/JDA-Utilities/3.0.2

Hi I am using the event waiter like this:

  
```
waiter.waitForEvent(GuildMemberJoinEvent::class.java, {true}) {
        rootLogger.info(it.member.effectiveName)

        val welcomeMessage = "Welcome!"
        it.member.guild.getTextChannelById(config.getLong("config.inviteChannelId"))!!.sendMessage(welcomeMessage).queue()
}
```

But sometimes the message does not appear in the channel, I suspect the EventWaiter is buggy and it doesn't trigger. Any idea?

**Comment by Andre601** [comment]
Why do you use JDA-Utilities for something that is in JDA?
Just listen for the GuildMemberJoinEvent and send a message then. Using an EventWaiter for this seems really out of place.

**Comment by jagrosh** [comment]
The event waiter only waits for an event one time, as per its documentation. To activate again, you'd need to wait again, but as noted, it seems like you should be using an Event Listener, not an Event Waiter.
